#spring.application.name=measurement
#
#db.url=jdbc:h2:mem:quantity_db;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
#db.user=sa
#db.password=
#db.driver=org.h2.Driver
#db.pool.size=10
#
#logging.level.root=INFO
#logging.level.com.app.quantitymeasurement=WARN


spring.application.name=quantity-measurement-app

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:h2:mem:quantity_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# LOGGING
# ===============================

logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# SWAGGER / OPENAPI
# ===============================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always